import React from "react";

const BENEFITS = [
  { icon: "↗", title: "Raise more for your cause", text: "Run joyful, shareable raffles that turn your community&apos;s support into meaningful fundraising.", tone: "from-[#9d45e3] to-[#6d27ca]" },
  { icon: "♡", title: "Engage your supporters", text: "Give people a simple, exciting reason to get involved with the causes they care about.", tone: "from-[#1fc3f2] to-[#1099e5]" },
  { icon: "✦", title: "Easy to run competitions", text: "From set-up to winner selection, we&apos;re designing every step to feel clear and stress-free.", tone: "from-[#a948e5] to-[#20b8ef]" },
  { icon: "✓", title: "Safe, legal & compliant", text: "A trusted platform built around transparency, security and responsible fundraising.", tone: "from-[#17b9ec] to-[#4e54d6]" },
];

export default function InterestBenefits() {
  return <section className="mx-auto max-w-6xl"><div className="mx-auto max-w-2xl text-center"><span className="inline-flex rounded-full border border-[#a14de0]/20 bg-[#f3e9ff] px-4 py-2 text-[10px] font-black tracking-[.18em] text-[#6b2ac3] uppercase">Built for more good</span><h2 className="mt-5 text-4xl font-black leading-[.92] tracking-[-.055em] text-[#4e1ca6] sm:text-5xl">RAFFLES WITH<br /><span className="text-[#13abe7]">REAL IMPACT.</span></h2><p className="mt-5 text-sm leading-relaxed text-[#674c83] sm:text-base">A modern fundraising platform that brings charities and supporters closer together.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{BENEFITS.map((benefit, index) => <article key={benefit.title} className="group relative overflow-hidden rounded-[24px] border border-[#8d46d8]/13 bg-white p-6 shadow-[0_12px_32px_rgba(79,26,169,.08)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_38px_rgba(79,26,169,.16)]"><span className="absolute right-5 top-5 text-[10px] font-black text-[#a786cc]">0{index + 1}</span><div className={`flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br ${benefit.tone} text-2xl font-black text-white shadow-lg`}>{benefit.icon}</div><h3 className="mt-6 text-lg font-black leading-tight text-[#5720ad]">{benefit.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#71518f]">{benefit.text}</p><div className={`mt-6 h-1 w-9 rounded-full bg-gradient-to-r ${benefit.tone} transition-all duration-300 group-hover:w-full`} /></article>)}</div><div className="mt-12 flex flex-wrap items-center justify-center gap-x-9 gap-y-3 rounded-2xl border border-[#8650d0]/15 bg-white/70 px-6 py-5 text-[11px] font-bold text-[#654785] shadow-sm"><span>✓ Made for charities</span><span>✓ Supporter-first experience</span><span>✓ Powered by positive change</span></div></section>;
}
